name: Herbarium_Pipeline
channels:
  - bioconda
  - conda-forge
  - defaults
dependencies:
  - samtools=1.20.0
  - htslib=1.20.0
  - bwa=0.7.17
  - bowtie2=2.5.4
  - degenotate=1.3
  - pcangsd=1.21
  - fastp=0.23.4
  - fastqc=0.12.1  
  - python=3.10.6
